version: '3.9'
services:
  account-svc:
    build: ./src/account-svc
    ports: ['3001:3000']
  content-svc:
    build: ./src/content-svc
    ports: ['3002:3000']
  analytics-svc:
    build: ./src/analytics-svc
    environment:
      - REDIS_URL=redis://redis:6379
    ports: ['3003:3000']
  redis:
    image: redis:7-alpine
    networks:
      - internal_net
networks:
  internal_net:
    driver: bridge
