apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: custom-istio
spec:
  profile: demo                            # вместо demo можно default/remote/ambient по нуждам
  meshConfig:
    defaultConfig:
      concurrency: 2
  values:
    global:
      jwtPolicy: first-party-jwt           # ← явный выбор first-party JWT :contentReference[oaicite:1]{index=1}
