apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: custom-istio
spec:
  profile: demo                            
  meshConfig:
    defaultConfig:
      concurrency: 2
  values:
    global:
      jwtPolicy: first-party-jwt           
