apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
        role: backend
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: auth-svc
          image: auth-svc:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: CERT_DIR
              value: /certs
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: tls
              mountPath: /certs
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: tls
          secret:
            secretName: tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: microservices
spec:
  selector:
    app: auth-svc
  ports:
    - port: 80
      targetPort: 3000
