apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids-agent
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ids-agent
  template:
    metadata:
      annotations:             
        sidecar.istio.io/proxyCPU: "200m"
        sidecar.istio.io/proxyMemory: "256Mi"
        proxy.istio.io/config: |
          {"holdApplicationUntilProxyStarts": true}
      labels:
        app: ids-agent
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: ids-agent
          image: ids-agent:latest
          imagePullPolicy: IfNotPresent

          startupProbe:
            exec: { command: ["bash","-c","echo ok"] }
            failureThreshold: 10      # 20 с
            periodSeconds: 2
          readinessProbe:
            exec: { command: ["bash","-c","echo ok"] }
            periodSeconds: 10
          livenessProbe:
            exec: { command: ["bash","-c","pgrep -f agent.py"] }
            periodSeconds: 30
          env:
            - name: SIEM_URL
              value: http://siem.local/ingest
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ids-agent
  namespace: microservices
spec:
  selector:
    app: ids-agent
  ports:
    - name: http
      port: 80
      targetPort: 3000
