apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-svc
  namespace: microservices
  labels: { app: monolith-svc }
spec:
  replicas: 1
  selector:
    matchLabels: { app: monolith-svc }
  template:
    metadata:
      labels: { app: monolith-svc }
    spec:
      containers:
        - name: monolith
          image: monolith-svc:ci
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:   { cpu: 500m, memory: 256Mi }
            requests: { cpu: 250m, memory: 128Mi }
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
            seccompProfile: { type: RuntimeDefault }

---
apiVersion: v1
kind: Service
metadata:
  name: monolith-svc
  namespace: microservices
  labels: { app: monolith-svc }
spec:
  selector: { app: monolith-svc }
  ports:
    - port: 80          # как и раньше видит кластер
      targetPort: 8080  # реальный порт приложения
      protocol: TCP
