# k8s/monolith.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-svc
  namespace: microservices
  labels: { app: monolith-svc }
spec:
  replicas: 1
  selector:
    matchLabels: { app: monolith-svc }
  template:
    metadata:
      labels: { app: monolith-svc }
    spec:
      containers:
        - name: monolith
          image: monolith-svc:ci
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080           # порт внутри контейнера
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: monolith-svc
  namespace: microservices
  labels: { app: monolith-svc }
spec:
  selector: { app: monolith-svc }
  ports:
    - port: 80           # порт, на который обращаются клиенты внутри кластера
      targetPort: 8080   # реальный порт приложения в контейнере
      protocol: TCP
