apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: microservices
type: kubernetes.io/tls
stringData:
  tls.crt: PLACEHOLDER_CERT
  tls.key: PLACEHOLDER_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: microservices
type: Opaque
stringData:
  secret: demo-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: crypto-key
  namespace: microservices
type: Opaque
stringData:
  key: dummy-key
