
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-svc
spec:
  template:
    spec:
      containers:
      - name: account-svc
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
$patch: merge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-svc
spec:
  template:
    spec:
      containers:
      - name: analytics-svc
        readinessProbe:
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
$patch: merge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc
spec:
  template:
    spec:
      containers:
      - name: auth-svc
        readinessProbe:
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
$patch: merge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-svc
spec:
  template:
    spec:
      containers:
      - name: content-svc
        readinessProbe:
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
$patch: merge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-svc
spec:
  template:
    spec:
      containers:
      - name: crypto-svc
        readinessProbe:
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
$patch: merge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids-agent
spec:
  template:
    spec:
      containers:
      - name: ids-agent
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
$patch: merge