# Патч для оптимизации probes под нагрузочное тестирование
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy  # Kustomize применит ко всем deployments
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: dummy
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5           # увеличено с 2
          failureThreshold: 10       # уменьшено с 30
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15    # уменьшено с 30
          periodSeconds: 10          # увеличено с 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30          # увеличено с 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5