apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids-agent
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ids-agent
  template:
    metadata:
      annotations:             
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        traffic.sidecar.istio.io/excludeInboundPorts: "3000"
        status.sidecar.istio.io/port: "0"
        sidecar.istio.io/proxyCPU: "200m"
        sidecar.istio.io/proxyMemory: "256Mi"
        proxy.istio.io/config: |
          {"holdApplicationUntilProxyStarts": true}
      labels:
        app: ids-agent
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      hostPID: false
      containers:
        - name: ids-agent
          image: ids-agent:latest
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3000
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15 
            failureThreshold: 30
            periodSeconds: 2

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 30

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 30

          env:
            - name: SIEM_URL
              value: http://siem.local/ingest
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          resources:
            requests: { cpu: "150m", memory: "256Mi" }
            limits:   { cpu: "750m", memory: "512Mi" }
          securityContext:
            capabilities: { drop: ["ALL"] }
            seccompProfile: { type: RuntimeDefault }
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ids-agent
  namespace: microservices
spec:
  selector:
    app: ids-agent
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ids-agent
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ids-agent
  minReplicas: 4
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 70 }